spring:
  application:
    name: GamesShop
  datasource:
    url: jdbc:mysql://localhost:3307/gamesshop
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    org.springframework.web: DEBUG

jwt:
  key: 48v2+wyPoUvM22gBDawqJXhe7C3FOVpp8PJlH4XOAcY=
  tokenExpirationMs: 3600000

upload:
  path: D:\ws-shopgame-01\Game_Shop\Game_Shop\src\data\images