spring:
  application:
    name: GamesShop
  datasource:
    url: jdbc:mysql://localhost:3307/gamesshop
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: none

jwt:
  key: 48v2+wyPoUvM22gBDawqJXhe7C3FOVpp8PJlH4XOAcY=